twig:
    default_path: '%kernel.project_dir%/templates'

    # use tailwind css on forms
    form_themes: [
        'zsf-tailwind-forms-themes/custome_layout.html.twig'
    ]

when@test:
    twig:
        strict_variables: true
